Metrics/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/AlignHash:
  EnforcedColonStyle: table
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
