---
message: |
  - hygen {bold jg} {bold example} --name NAME
  - hygen {bold jg} {bold page} --name NAME
  - hygen {bold jg} {bold pane} --name NAME
  - hygen {bold jg} {bold part} --name NAME --pane PARENT
  - hygen {bold jg} {bold part} --name NAME --page PARENT
  - hygen {bold jg} {bold part} --name NAME --styled PARENT
  - hygen {bold jg} {bold part} --name NAME --example PARENT
  - hygen {bold jg} {bold styled} --name NAME
---
