default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
#  host: <%#= Rails.application.credentials.db.dig(:cultages, :host) %>
#  port: <%#= Rails.application.credentials.db.dig(:cultages, :port) %>
#  username: <%#= Rails.application.credentials.db.dig(:cultages, :user) %>
#  password: <%#= Rails.application.credentials.db.dig(:cultages, :pass) %>

development:
  <<: *default
  database: cultages_development

test:
  <<: *default
  database: cultages_test

production:
  <<: *default
  database: cultages

