default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
#  host: <%#= Rails.application.credentials.db.dig(:cultage, :host) %>
#  port: <%#= Rails.application.credentials.db.dig(:cultage, :port) %>
#  username: <%#= Rails.application.credentials.db.dig(:cultage, :user) %>
#  password: <%#= Rails.application.credentials.db.dig(:cultage, :pass) %>

development:
  <<: *default
  database: cultage_development

test:
  <<: *default
  database: cultage_test

production:
  <<: *default
  database: cultage

